/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 menuzef.gltf 
Author: PolyChromic (https://sketchfab.com/PolyChromicDesing)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/marshmallow-48290f2ff86f45e79e86b6e7576befd2
Title: Marshmallow
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/menuzef.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCube1_lambert2_0.geometry} material={materials.lambert2} position={[0, 0.75, 0]} scale={[0.803, 1, 0.803]} />
      <mesh geometry={nodes.pCube2_lambert3_0.geometry} material={materials.lambert3} position={[0, 0.75, 0]} scale={[0.803, 1, 0.803]} />
      <mesh geometry={nodes.Ice_Cube_V2pCube3_lambert4_0.geometry} material={materials.lambert4} position={[0.15, 0.25, 0]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes.Ice_Cube_V2pCube4_lambert4_0.geometry} material={materials.lambert4} position={[-0.15, 0.25, 0]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes.Ice_Cube_V2pCube6_lambert4_0.geometry} material={materials.lambert4} position={[-0.467, 0.807, 0.101]} rotation={[0.389, 0.032, -2.767]} scale={[0.044, 0.467, 0.044]} />
      <mesh geometry={nodes.pCube6_lambert4_0.geometry} material={materials.lambert4} position={[0.47, 0.807, 0.101]} rotation={[1.655, 1.181, 1.868]} scale={[0.044, 0.467, 0.044]} />
    </group>
  )
}

useGLTF.preload('/menuzef.gltf')
